require("user.keymaps")
require("user.options")
require("user.plugins")
require("user.colorscheme")
require("user.telescope")
require("user.whichkey")
require("user.proyect")
require("user.treesitter")
