local opts = vim.opt
opts.backup = false                          -- creates a backup file
opts.clipboard = "unnamedplus"               -- allows neovim to access the system clipboard
opts.cmdheight = 2                           -- more space in the neovim command line for displaying messages
--opts.completeopt = { "menuone" "noselect" } -- mostly just for cmp
opts.conceallevel = 0                        -- so that `` is visible in markdown files
opts.fileencoding = "utf-8"                  -- the encoding written to a file
opts.hlsearch = true                         -- highlight all matches on previous search pattern
opts.ignorecase = true                       -- ignore case in search patterns
opts.mouse = "a"                             -- allow the mouse to be used in neovim
opts.pumheight = 10                          -- pop up menu height
opts.showmode = false                        -- we don't need to see things like -- INSERT -- anymore
opts.showtabline = 2                         -- always show tabs
opts.smartcase = true                        -- smart case
opts.smartindent = true                      -- make indenting smarter again
opts.splitbelow = true                       -- force all horizontal splits to go below current window
opts.splitright = true                       -- force all vertical splits to go to the right of current window
opts.swapfile = false                        -- creates a swapfile
opts.termguicolors = true                    -- set term gui colors (most terminals support this)
opts.timeoutlen = 100                        -- time to wait for a mapped sequence to complete (in milliseconds)
opts.undofile = true                         -- enable persistent undo
opts.updatetime = 300                        -- faster completion (4000ms default)
opts.writebackup = false                     -- if a file is being edited by another program (or was written to file while editing with another program) it is not allowed to be edited
opts.expandtab = true                        -- convert tabs to spaces
opts.shiftwidth = 2                          -- the number of spaces inserted for each indentation
opts.tabstop = 2                             -- insert 2 spaces for a tab
opts.cursorline = true                       -- highlight the current line
opts.number = true                           -- set numbered lines
opts.relativenumber = true                  -- set relative numbered lines
opts.numberwidth = 4                         -- set number column width to 2 {default 4}
opts.signcolumn = "yes"                      -- always show the sign column otherwise it would shift the text each time
opts.wrap = false                            -- display lines as one long line
opts.scrolloff = 8                           -- is one of my fav
opts.sidescrolloff = 8
opts.guifont = "monospace:h17"               -- the font used in graphical neovim applications


vim.transparent_window = true